### ISSUE TITLE
Feature request: report which courses have Materia enabled

### ISSUE THREAD

**Issue by mrash2** [ucfopen/Materia#1441]
Hi there,

Since the Materia LTI is installed at the account level in Canvas, default LTI reports only tell us that it is enabled in the account. However, what we're really interested in is which (or at least how many) courses have the LTI enabled in course navigation. Is it possible to build this into some sort of admin panel or other area within Materia?

We're trying to figure out a way to get at this info without scripting REST calls and/or sifting through the Canvas Data Portal for this info. Any thoughts?

**Comment by clpetersonucf** [comment]
This feature idea may unfortunately live slightly outside what we're able to realistically do since it's so specific to a particular LMS. I talked to some of the folks who work more directly in Canvas and it sounds like no matter what, it would require a script running custom queries either in a custom application or in a dedicated data analysis tool like redash. The API does provide this information at the course level via https://canvas.instructure.com/doc/api/external_tools.html#method.external_tools.visible_course_nav_tools - however, the query would still have to be run against every course at your institution, which would be very slow.

After the upcoming React conversion, we'll be working on some updates to LTI as a whole, and it's possible we can reassess what is feasible at that point. Currently however, this isn't really something on our roadmap.

**Comment by mrash2** [comment]
Thanks, Corey - I understand. I had originally tried a few different approaches to getting this via API, but kept bumping into the 100-record limit on this call. Thankfully, I remembered checking with UCF's team about possibly using the canvasapi wrapper for this and Matthew Jones hooked me up with a script that, with some minor tweaking, accomplishes this on Google Colab. Y'all are just a great group!

**Comment by clpetersonucf** [comment]
Great to hear you found a solution!
