### ISSUE TITLE
Nobody understands that linking to a Materia widget in a LMS won't sync scores

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Materia#186]
It's very obvious based on the tickets that I handle that it's very common to link to a Materia widget from Canvas and expect the scores to magically sync to the gradebook.

We need to investigate a few ideas:
1. Perhaps explain on the widget instance page on Materia the different ways to embed a widget
2. Perhaps exclude direct access to a widget if it has been used inside an LTI
3. Some magical third option

**Comment by iturgeon** [comment]
We recently added an inline link to help, but this should be considered a half measure.  
<img width="691" alt="Screen Shot 2019-06-03 at 8 21 56 PM" src="https://user-images.githubusercontent.com/73480/58842671-5513d180-863d-11e9-966b-2bbb25ff584c.png">

**Comment by iturgeon** [comment]
Also, we should consider using the technique Obojobo Next uses for assignments vs content external tools (since canvas uses different urls for them).

## Content Module
<img width="783" alt="Screen Shot 2019-06-03 at 8 25 38 PM" src="https://user-images.githubusercontent.com/73480/58842796-c5225780-863d-11e9-8759-0336d704f675.png">

## Assignment
<img width="505" alt="Screen Shot 2019-06-03 at 8 25 03 PM" src="https://user-images.githubusercontent.com/73480/58842815-d703fa80-863d-11e9-9383-c4cece2da898.png">

This takes advantage of some of Canvas's custom settings as shown in https://github.com/ucfopen/Obojobo/blob/1e657f98b3a6baea2c4399c7d043fb9407b52d28/packages/app/obojobo-express/views/lti_config_xml.ejs#L14-L59
